apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: hacbs-test-project-42cg
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: hacbs-test-project-42cg
    app.kubernetes.io/part-of: rhtap-demo-app
  name: hacbs-test-project-42cg
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: hacbs-jvm-build-test-project
      app.kubernetes.io/instance: hacbs-test-project-42cg
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: hacbs-jvm-build-test-project
        app.kubernetes.io/instance: hacbs-test-project-42cg
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-cwqa-tenant/rhtap-demo-app/hacbs-test-project-42cg@sha256:4474be806db00b317948836b64a323817e7c6c9c200aab97009ed6b329f84f2a
        name: hacbs-jvm-build-test-project
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
status: {}
